#! /bin/bash
kubectl get nodes -o json | jq -r '.items[] | [.metadata.labels."alpha.eksctl.io/nodegroup-name",.metadata.labels."kubernetes.io/hostname",.status.capacity.pods,.status.nodeInfo.kubeletVersion,.metadata.creationTimestamp,.metadata.labels."node.kubernetes.io/instance-type"] | @tsv'
